pipeline{
    agent any
    stages{
        stage("Sonar quality check"){
            agent{
                docker{
                    image 'openjdk:11'
                }
            }
            steps{
                script{
                    withSonarQubeEnv(credentialsId: 'sonar-token') {
                        sh" ${SCANNER_HOME**}**}/bin/sonar-scanner \
                              -Dsonar.projectKey=simple_webapp \
                              -Dsonar.sources=. "
                        sh 'mvn "-Dsonar.qualitygate=true" sonar:sonar'
                    }
                }
            }
        }
    }
}