pipeline{
    agent any
    tools {
          maven 'MAVEN_HOME'
     }
    stages{
        stage("Sonar quality check"){
            agent{
                docker{
                    image 'openjdk:11'
                }
            }
            steps{
                script{
                    withSonarQubeEnv(credentialsId: 'sonar-token') {
                        sh 'chmod +x mvnw'
                        sh 'mvn "-Dsonar.qualitygate=true" sonar:sonar'
                    }
                }
            }
        }
    }
}