spring:
  output:
    ansi:
      enabled: always
  application:
    name: GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: SECURITY
          uri: lb://SECURITY
          predicates:
            - Path=/auth/**
          filters:
            - AuthFilter
            - RewritePath=/auth/(?<path>.*), /$\{path}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080