server:
  servlet:
    context-path: /
  port: 9898

spring:
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

openapi:
  service:
    title: Auth Service
    version: 1.0.0
    url: http://localhost:8080

springdoc:
  enable-native-support: true
  api-docs:
    path: /auth/v3/api-docs
  swagger-ui:
    path: /auth/swagger-ui.html

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  jaeger:
    tracing:
      url: http://localhost:4318/v1/traces

